# Configures the base url for Ollama Server
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define the model ID that langchain4j will call in Ollama Server
quarkus.langchain4j.ollama.chat-model.model-id=gemma3:4b

# Define timeout
# If model response time is open after 60s, the request will fail
quarkus.langchain4j.ollama.timeout=60s

quarkus.langchain4j.easy-rag.path=src/main/resources/rag
quarkus.langchain4j.embedding-model.provider=ollama
quarkus.langchain4j.ollama.embedding-model.model-name=nomic-embed-text
