# Configures the base url for Ollama Server
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define the model ID that langchain4j will call in Ollama Server
quarkus.langchain4j.ollama.chat-model.model-id=gemma3:4b

# Define timeout
# If model response time is open after 60s, the request will fail
quarkus.langchain4j.ollama.timeout=60s

quarkus.langchain4j.embedding-model.provider=ollama
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# PostgreSQL + pgvector (required by quarkus-langchain4j-pgvector)
# Start with: docker compose up -d
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=travel
quarkus.datasource.password=travel
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/travel

# the dimension of vector need to match EmbeddingModel.
# nomic-embed-text = 768 dimensions
quarkus.langchain4j.pgvector.register-vector-pg-extension=true

quarkus.langchain4j.pgvector.dimension=768

# create table
quarkus.langchain4j.pgvector.table=travel_embeddings

# just for dev env
quarkus.langchain4j.pgvector.drop-table-first=true

quarkus.log.category."dev.langchain4j".level=DEBUG
quarkus.log.category."io.quarkiverse.langchain4j".level=DEBUG
